simple/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include, handler404, handler500
from django.conf.urls.static import static

#JEFFfrom django.contrib.flatpages import views as fviews

#JEFFfrom django.views.generic import TemplateView

from simple import views

urlpatterns = patterns('',
    #url( r'^int/$', views.staticViewJson, name="homePageView" ),
    #url( r'^int/(?P<category>news)/(?P<year>[\d]+)/(?P<slug>[\w\s-]+)/$', views.catPageViewJson, name="newsPostViewJason" ),
    #url( r'^int/(?P<category>ideas)/(?P<year>[\d]+)/(?P<slug>[\w\s-]+)/$', views.catPageViewJson, name="ideaViewJason" ),
    #url( r'^int/(?P<category>news)/$', views.listViewJson, name="newsViewJason" ),
    #url( r'^int/(?P<category>ideas)/$', views.listViewJson, name="ideasViewJason" ),
    #url( r'^int/(?P<slug>[\w\s-]+)/$', views.staticViewJson, name="pageViewJason" ),

    #for all my various pages WITHOUT json
    url( r'^$', views.staticView, name="homePageView" ),
    url( r'^(?P<category>news)/(?P<year>[\d]+)/(?P<slug>[\w\s-]+)/$', views.catPageView, name="newsPostView" ),
    url( r'^crew/(?P<pk>[\d]+)/$', views.crewView, name="crewView" ),
    url( r'^(?P<category>crews)/$', views.crewsView, name="crewsView" ),
    url( r'^(?P<category>news)/$', views.listView, name="newsView" ),
    url( r'^(?P<category>photos)/$', views.listView, name="photosView" ),
    url( r'^(?P<category>photos)/(?P<album>[\w\s-]+)/$', views.albumView, name="albumView" ),
    url( r'^(?P<slug>[\w\s-]+)/$', views.staticView, name="pageView" ),


    url( r'^submitContactForm$', views.submitContactForm, name="submitContactForm" ),
    #url( r'^submitKudos$', views.submitKudos, name="submitKudos" ),

    # UCBC static content view definitions
    #JEFFurl(r'^$', fviews.flatpage, {'url': '/'}, name='home'),
    #JEFFurl(r'^about/$', fviews.flatpage, {'url': '/about/'}, name='about'),
    #JEFFurl(r'^committee/$', fviews.flatpage, {'url': '/committee/'}, name='committee'),
    #JEFFurl(r'^contact/$', fviews.flatpage, {'url': '/contact/'}, name='contact'),
    #JEFFurl(r'^boats/$', fviews.flatpage, {'url': '/boats/'}, name='boats'),
    #JEFFurl(r'^boathouse/$', fviews.flatpage, {'url': '/boathouse/'}, name='boathouse'),
    #JEFFurl(r'^crews/$', fviews.flatpage, {'url': '/crews/'}, name='crews'),
    #JEFFurl(r'^news/$', fviews.flatpage, {'url': '/news/'}, name='news'),
    #JEFFurl(r'^get-involved/$', fviews.flatpage, {'url': '/get-involved/'}, name='get-involved'),
    #JEFFurl(r'^sponsors-alumni/$', fviews.flatpage, {'url': '/sponsors-alumni/'}, name='sponsors-alumni'),
    #JEFFurl(r'^gallery/$', fviews.flatpage, {'url': '/gallery/'}, name='gallery'),
    #url(r'^(?P<url>.*/)$', 'flatpage'), # Supposed to be a flatpage catch-all but doesn't seem to work...
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ucbc/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls import handler404, handler500, handler403
from django.contrib import admin
from filebrowser.sites import site

#from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/filebrowser/', include(site.urls)),
    url( r'^admin/', include( admin.site.urls ) ),
    url( r'^', include( 'simple.urls', namespace = 'simple' ) ),
)

#FIXME - DO I NEED THIS GUY?
#urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.MEDIA_URL + settings.FILEBROWSER_VERSIONS_BASEDIR, document_root=settings.MEDIA_ROOT )
#print settings.MEDIA_URL + settings.FILEBROWSER_VERSIONS_BASEDIR

handler404 = 'simple.views.handler404'
handler403 = 'simple.views.handler403'

simple/views.py
from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseNotFound
from django.http import Http404
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.views.generic import ListView
from simple.models import Page, Category, Crew, Image
from django.template import loader, Context
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied
from django.conf import settings
import re
import json
from django.db.models import Q
import markdown
from django import template

from filebrowser.sites import site
from filebrowser.base import FileListing
from filebrowser.base import FileObject
from filebrowser.settings import DIRECTORY as FB_DIRECTORY
from os.path import join

from random import shuffle
from random import randint

class ContactForm( forms.Form ):
    defaultAttr = [ ( 'required', '' ), ( 'class', 'input' ) ]

    subject     = forms.CharField( max_length=100, widget = forms.TextInput(attrs = dict( defaultAttr + [ ( 'placeholder', 'Subject' ) ] ) ) )
    message     = forms.CharField( max_length=1000, widget = forms.Textarea(attrs=dict( defaultAttr + [ ( 'placeholder', 'Message' ) ] ) ), label="Message" )
    sendername  = forms.CharField( max_length=100, label="Name", widget = forms.TextInput(attrs=dict( defaultAttr + [ ( 'placeholder', 'Your Name' ) ] ) ) )
    senderemail = forms.EmailField( label="Email", widget = forms.TextInput(attrs=dict( defaultAttr + [ ( 'placeholder', 'Your Email' ) ]  ) ) )

def ensurePermission( page, request ):
    if page.status == 0 and not request.user.is_authenticated():
        raise PermissionDenied

def getImage( originalImage, size ):
    if size:
        imageURL = loader.render_to_string( 'simple/subs/image.html', { 'fileObject': originalImage, 'size': size } )
    else:
        imageURL = loader.render_to_string( 'simple/subs/image.html', { 'fileObject': originalImage } )
    return imageURL.strip()

def paragraphedPageContent( page, includeImages = True, stopAt = None ):
    content = page.content1
    imageTagsAndLocations = re.findall( r'\[\[([\w\s/\\]*);([\w\s/\\]*)(;*[\w\s/\\]*)\]\]', content )
    for (imageTag,imageLocation,imageSize) in imageTagsAndLocations:
        imageSizeOriginal = imageSize
        if includeImages:
            if len( imageSize ) == 1:
                imageSize = None
            elif len( imageSize ) == 0:
                imageSize = 'medium'
            else:
                imageSize = imageSize[1:].lower()
            if imageLocation == 'left' or imageLocation == 'right':
                css = "display:block; float:" + imageLocation
                captionCss = "text-align:left"
            elif imageLocation == 'center' or imageLocation=='centre':
                css="display:block; margin-left:auto; margin-right:auto"
                captionCss = 'text-align:center'
            else:
                css = ''
                captionCss = ''
            try:
                try:
                    imageInstance = page.images.get(title=imageTag)
                except:
                    imageInstance = get_object_or_404( Image, title=imageTag )

                if imageInstance.imageFile.is_version:
                    originalImage = imageInstance.imageFile.original
                else:
                    originalImage = imageInstance.imageFile
                if originalImage.exists:
                    imageURL = getImage( originalImage, imageSize )

                    if len( imageInstance.caption ) > 0:
                        if imageLocation == 'center' or imageLocation=='centre':
                            newImageTag = '<img style="' + css + '" src="' + imageURL + '" alt="'+ imageInstance.title + '">'
                        else:
                            newImageTag = '<img src="' + imageURL + '" alt="'+ imageInstance.title + '">'
                        newImageTag = '<figure style="' + css + '">' +newImageTag + '<figcaption style="' + captionCss + '"><i>' + imageInstance.caption + '</i></figcaption></figure>'
                    else:
                        newImageTag = '<img style="' + css + '" src="' + imageURL + '" alt="'+ imageInstance.title + '">'
                    content = content.replace( '[[' + imageTag + ';' + imageLocation + imageSizeOriginal + ']]', newImageTag )
                else:
                    print 'File does not exist for tag: ', imageTag
            except Exception as inst:
                print 'Failed to get image ', imageTag, ':', inst
        else:
            content = content.replace( '[[' + imageTag + ';' + imageLocation + imageSizeOriginal + ']]', '' )

    if stopAt != None:
        totalLength = len( content )
        content = content[ 0:min( stopAt , len( content ) ) ]
        if stopAt < totalLength:
            content = content + ' ....'

    return markdown.markdown( content )

def extraContextItems():
    form = ContactForm()

    #page     = Page.objects.get(slug='news')
    posts    = Page.objects.filter(status=1,categories__name='newspost' ).order_by( '-created' )
    maxPosts = min( len( posts ), 8 )
    posts    = posts[0:maxPosts-1]

    postsToPrint = []

    for post in posts:
        postDic = {}
        postDic[ 'title' ] = post.title
        postDic[ 'year' ]  = post.created.year
        postDic[ 'slug' ]  = post.slug
        images = post.images.all()
        postDic[ 'image' ] = '/media/uploads/siteStatic/crest.png'
        foundImage = False

        if len( images ) > 0:
            i = randint( 0, len( images ) - 1 )
            foundImage = True
            imageFile = images[ i ].imageFile
        else:
            crews = post.crew_set.all()
            if len( crews ) > 0:
                is1 = range( 0, len( crews ) )
                shuffle( is1 )
                for i in is1:
                    images = crews[ i ].images.all()
                    if len( images ) > 0:
                        i = randint( 0, len( images ) - 1 )
                        foundImage = True
                        imageFile = images[ i ].imageFile
                        break

        if foundImage:
            if imageFile.is_version:
                originalImage = imageFile.original
            else:
                originalImage = imageFile
            mediumURL = getImage( originalImage, 'medium' )

            postDic[ 'image' ] = mediumURL

        postsToPrint.append( postDic )

    templateName = 'simple/subs/sideNews.html'
    sideNews = loader.render_to_string( templateName, { 'posts': postsToPrint } )

    try:
        footerPage = Page.objects.get(slug='hidden-footer')
        footer = paragraphedPageContent( footerPage )
    except:
        footer = 'the boat club president is a nerd'

    try:
        navPage = Page.objects.get(slug='navs')
        navs = navPage.content1
    except:
        navs = 'Menus Not Found'

    return [( 'contactform', form ), ( 'footer', footer ), ('sideNews', sideNews ), ('navs', navs ) ]

def renderWithDefaults( request, context ):

    extras = extraContextItems()
    newContext = dict(  context.items() + extras )
    return render( request, 'simple/page.html', newContext )


def catPageViewStuff( category, year, slug, json, request ):
    ensureList( category )

    myCat = Category.objects.get(name=category).subCategoryName
    page = get_object_or_404( Page, slug=slug, created__year=year, categories__name=myCat )

    ensurePermission( page, request )

    if json:
        returnDic = page.pageDict()
    else:
        returnDic = {'page':page}

    templateName = 'simple/subs/' + myCat + '.html'
    pageContent = paragraphedPageContent( page )

    returnDic[ 'htmlContent' ] = loader.render_to_string( templateName, { 'page': page, 'pageContent': pageContent, 'path': request.path } )

    return returnDic

def catPageView( request, category, year, slug ):
    context = catPageViewStuff( category, year, slug, False, request )
    return renderWithDefaults( request, context )

def catPageViewJson( request, category, year, slug ):
    returnDic = catPageViewStuff( category, year, slug, True, request )
    return HttpResponse( json.dumps( returnDic , cls=DjangoJSONEncoder), content_type = 'application/json' )

def ensureList( category ):
    category = Category.objects.get(name=category)
    if len( category.subCategoryName ) == 0:
        raise Http404

def imagesFromSubfolder( subfolder ):

    directory = FB_DIRECTORY

    path = u'%s' % join( directory, 'gallery', subfolder )

    filelisting = FileListing(
        path,
        #filter_func=filter_browse,
        sorting_by='name',
        sorting_order='desc',
        #site=self
        )

    images = []

    for fileObject in filelisting.files_walk_filtered():#files_walk_total():
        image = {}
        if fileObject.width != None:
            thumbnail = getImage( fileObject, 'thumbnail' )
            fileName  = fileObject.url
            #thumbnail = loader.render_to_string( 'simple/subs/image.html', { 'fileObject': fileObject, 'size': 'thumbnail' } )
            #fileName  = loader.render_to_string( 'simple/subs/image.html', { 'fileObject': fileObject } )
            image[ 'url' ] = fileName
            image[ 'thumbnailUrl' ] = thumbnail
            image[ 'title' ] = fileObject.filename_root
            images.append( image )
    return images;

def albumView( request, category, album ):
    page = get_object_or_404( Page, slug=album, categories__name='album' )
    ensurePermission( page, request )
    context = {'page':page}

    images = imagesFromSubfolder( album )
    shuffle( images )
    templateName = 'simple/subs/album.html'
    pageContent = paragraphedPageContent( page );
    context[ 'htmlContent' ] = loader.render_to_string( templateName, { 'page': page, 'pageContent': pageContent, 'images': images} )

    return renderWithDefaults( request, context )

simple/templates/simple/subs/album.html
{% load staticfiles %}

{{pageContent | safe }}
<div id="blueimp-gallery" class="gallery blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

<div id="links" class="gallery">
    {% for image in images %}<a href="{{ image.url }}" title="{{ image.title }}"><img src="{{ image.thumbnailUrl }}" alt="{{ image.title }}"></a>{% endfor %}
</div>

<br>
<a class='jaxify' href="{% url 'simple:photosView' 'photos' %}"><i class="fa fa-arrow-circle-left fa-1x"></i> back to Album List</a>


<script src="{%static 'simple/js/vendor/gallery/js/blueimp-gallery.min.js' %}"></script>
<script>
document.getElementById('links').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
};
</script>

simple/templates/simple/subs/crew.html
{% load staticfiles %}

<br>
{% if pageContent|length %}
<h2>Results</h2>
{{pageContent | safe }}
{% endif %}

<h2>Crew Order</h2><br>
<ul>
{% for seat in seats %}
    <li>{{seat|first}}:
        <i>{% with seat|last as member %}{{member.name}}{% endwith %}</i>
    </li>
{% endfor %}
{% if crew.coxes.all|length %}
<li>Cox:
{% for cox in crew.coxes.all %}
    <i>{{cox.name}},</i>
{% endfor %}
{% endif %}
</li>
</ul>
{% if crew.subs.all|length %}
<h4><span class="Seat">Subs:
{% for sub in crew.subs.all %}
    <i>{{sub.name}},</i></span>
{% endfor %}
</h4>
<br>
{% endif %}
{% if crew.coaches.all|length %}
<h4><span class="Seat">Coach:
{% for coach in crew.coaches.all %}
    <i>{{coach.name}},</i></span>
{% endfor %}
</h4>
<br>
{% endif %}
{% if crew.reports.all|length %}
<br>
<h2>Reports</h2>
<ul>
{% for page in crew.reports.all %}
    <li><a href="{% url 'simple:newsPostView' 'news' page.created.year page.slug %}">{{page.title}}</a></li>
{% endfor %}
</ul>
{% endif %}
{% if crew.boat %}
<h2>Raced in </h2>
<p>{{crew.boat.name}} ({{crew.boat.boatClass}})</p>
{% endif %}
<br>
<h2>Crew Photos</h2>

<div id="blueimp-gallery" class="gallery blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<div id="links" class="gallery">
    {% for image in images %}
    <a href="{{ image.url }}" title="{{ image.title }}">
        <img src="{{ image.thumbnailUrl }}" alt="{{ image.title }}">
    </a>
    {% endfor %}
</div>

<br>
<br>
<a class='jaxify' href="{% url 'simple:crewsView' 'crews' %}"><i class="fa fa-arrow-circle-left fa-1x"></i> back to Crews List</a>

<script src="{%static 'simple/js/vendor/gallery/js/blueimp-gallery.min.js' %}"></script>
<script>
document.getElementById('links').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
};
</script>

simple/templates/simple/subs/crews.html
{{pageContent | safe }}
    <ul>
    {% for seasonAndCrews in crewsBySeason %}

        <li>{{ seasonAndCrews | first }}
            <ul>
            {% with seasonAndCrews|last as compsAndCrews %}
                {% for compAndCrews in compsAndCrews %}
                <li>{{ compAndCrews | first }}
                    {% with compAndCrews|last as crews %}
                        <ul>
                            {% for crew in crews %}
                            <li><a class='jaxify' href="{% url 'simple:crewView' crew.id %}">{{crew.shortTitle}}</a></li>
                            {% endfor %}
                        </ul>
                    {% endwith %}
                </li>
                {% endfor %}
            {% endwith %}
            </ul>
        </li>
    {% endfor %}
    </ul>

simple/templates/simple/subs/image.html
{% load fb_versions %}{% if size %}{% version_object fileObject size as version_size %}{{version_size.url}}
{% else %}{{fileObject.url}}{% endif %}

simple/templates/simple/subs/menus.html
<!---IN case someone deletes the one on the site - although it will be in git anyway---->
<nav class="wideNav">
    <ul class='NavigationUL firstNav'>
        <li class="NavigationLI"><a class="mainColorBackground headerButton jaxify" href="/news/">News & Results</a>
        </li><li class="NavigationLI"><a class="mainColorBackground headerButton jaxify" href="/give/">Friends of UCBC</a>
        </li><li class="NavigationLI respectHover"><a class="mainColorBackground headerButton">Row For Univ</a>
        <ul class="secondNav">
            <li><a href="/novice/" class="mainColorBackground headerButton jaxify">Novice Rowing & Coxing</a>
            </li><li><a href="/experienced/" class="mainColorBackground headerButton jaxify">Experienced Rowing & Coxing</a>
            </li><li><a href="/safety/" class="mainColorBackground headerButton jaxify">Water Safety</a>
            </li><li><a href="/faqs/" class="mainColorBackground headerButton jaxify">FAQs</a>
            </li><li><a href="/head-porters-plate/" class="mainColorBackground headerButton jaxify">Awards</a></li>
        </li><li><a href="/blues/" class="mainColorBackground headerButton jaxify">Blues Rowers</a></li>
    </ul>
</li><li class="NavigationLI respectHover"><a class="mainColorBackground headerButton">About Us</a>
<ul class="secondNav">
    <li><a href="/fleet/" class="mainColorBackground headerButton jaxify">Our Fleet</a>
    </li><li><a href="/history/" class="mainColorBackground headerButton jaxify">Our History</a>
    </li><li><a href="/constitution/" class="mainColorBackground headerButton jaxify">Our Constitution</a>
    </li><li><a href="/boathouse/" class="mainColorBackground headerButton jaxify">Our Boathouse</a>
    </li><li><a href="/sponsors/" class="mainColorBackground headerButton jaxify">Our Sponsors</a>
    </li><li><a href="/blues/" class="mainColorBackground headerButton jaxify">Our Blues</a></li>
</ul>
</li><li class="NavigationLI"><a class="mainColorBackground headerButton jaxify" href="/crews/">Crews</a>
</li><li class="NavigationLI respectHover"><a class="mainColorBackground headerButton">Gallery</a>
<ul class="secondNav">
    <li><a href="/photos/" class="mainColorBackground headerButton jaxify">Photos</a></li>
    <li><a href="/videos/" class="mainColorBackground headerButton jaxify">Videos</a></li>
</ul>
</li><li class="NavigationLI"><a class="mainColorBackground headerButton jaxify" href="/committee/">Committee</a>
</li><li class="NavigationLI"><a href="/find-us/" class="mainColorBackground headerButton">Find Us</a></li>

</ul>
</nav>

simple/templates/simple/subs/news.html
    <ul>
    {% for post in postDics %}
        <li class="postLI"><a class='jaxify postTitle' href="{% url 'simple:newsPostView' page.slug post.post.created.year post.post.slug %}">{{post.post.title}}</a><span class="postDate smallItalicText">{{post.post.created|date:"M d, Y"}}</span>
            <div class="summary">{{post.summary | safe }}
            <a class='jaxify readFurther' href="{% url 'simple:newsPostView' page.slug post.post.created.year post.post.slug %}">Read further</a>
            </div>
        </li>
    {% endfor %}
    </ul>


<style>

    .postDate
    {
        margin-left: 15px;
        margin-bottom: 5px;
        display: block;
    }

    .postTitle
    {
        font-size: 1.3rem;
    }

    .postLI
    {
        background-color: rgba( 150, 150, 150, 0.2 );
        padding: 5px;
        margin-bottom: 30px;
        border-radiust: 10px;
        -webkit-box-shadow: 0px 0px 5px 0px rgba(150, 150, 150, 0.2);
        -moz-box-shadow:    0px 0px 5px 0px rgba(150, 150, 150, 0.2);
        box-shadow:         0px 0px 5px 0px rgba(150, 150, 150, 0.2);
    }

    .summary
    {
        margin-left: 15px;
        font-size: 0.9rem;
    }

    .readFurther
    {
        font-size: 0.7rem;
    }



</style>

simple/templates/simple/subs/newspost.html
<div class="shareWrapper">
    <a href="https://twitter.com/share" class="twitter-share-button" data-via="univbc" data-dnt="true">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <div class="fb-like" data-href="http://www.ucbc.org.uk{{ path }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
</div>
{{pageContent | safe }}
{% if page.crew_set.all|length > 0 %}
<h2>Crew</h2>
<ul>
{% for crew in page.crew_set.all %}
    <li><a href="{% url 'simple:crewView' crew.id %}">{{crew.title}}</a></li>
{% endfor %}
</ul>
{% endif %}
<br>
<p class="smallItalicText">Posted on {{page.created|date:"M d, Y"}}</p>

{% if page.tags.all|length %}
    <p class="postTags">posted under:
	{% for tag in page.tags.all %}<span class="postTag">{{tag.name}}</span>{% endfor %}
    </p>
{% endif %}

<a class='jaxify' href="{% url 'simple:newsView' 'news' %}"><i class="fa fa-arrow-circle-left fa-1x"></i> back to News and Results</a>

simple/templates/simple/subs/photos.html
{{pageContent | safe }}
    <ul>
    {% for album in postDics %}
        <li><a class='jaxify' href="{% url 'simple:albumView' 'photos' album.post.slug %}">{{album.post.title}}</a></li>
    {% endfor %}
    </ul>

simple/templates/simple/subs/sideNews.html
<div class="newsWrapper">

<div class="sideNews">
    {% for post in posts %}
    <div>
        <a href="{% url 'simple:newsPostView' 'news' post.year post.slug %}" class="sideNewsInner">
            <span>{{post.title}}</span>
            <img src="{{ post.image }}">
        </a>
    </div>
    {% endfor %}
    </div>
    <ul class="sideNews2">
    {% for post in posts %}
    <li><a href="{% url 'simple:newsPostView' 'news' post.year post.slug %}" class="sideNewsInner">{{post.title}}</a></li>
    {% endfor %}
    <li><a href="/news/" class="sideNewsInner">All News & Results...</a></li>
    </ul>

</div>

simple/templates/simple/subs/static.html
{{pageContent | safe }}

simple/templates/simple/subs/stuffilike.html
{{pageContent | safe }}
    <ul class="StuffILike">
    {% for tagName, tagThings in things.items %}
        <li class="TagLI"><a id="TAGID_{{tagThings.id}}">{{tagName}}</a>
        <ul class="TAGID_{{tagThings.id}}">
    	{% for thing in tagThings.things %}
	        <li class="ThingLI"><a href="{{thing.link}}"><strong>{{thing.title}}</strong></a>
	        <span class="smallItalicText">{{thing.description}}</span>
	        </li>
	    {% endfor %}
	    <p><span class="postTag CloseButton" id="TAGID_{{tagThings.id}}">Close</span></p>
	    </ul>
	    </li>
	{% endfor %}
    </ul>